2024-04-08 10:53:51,076 INFO    MainThread:33176 [wandb_setup.py:_flush():76] Current SDK version is 0.16.6
2024-04-08 10:53:51,077 INFO    MainThread:33176 [wandb_setup.py:_flush():76] Configure stats pid to 33176
2024-04-08 10:53:51,077 INFO    MainThread:33176 [wandb_setup.py:_flush():76] Loading settings from C:\Users\RyukiRi\.config\wandb\settings
2024-04-08 10:53:51,077 INFO    MainThread:33176 [wandb_setup.py:_flush():76] Loading settings from E:\Projects\CLIP\wandb\settings
2024-04-08 10:53:51,077 INFO    MainThread:33176 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-04-08 10:53:51,077 INFO    MainThread:33176 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-04-08 10:53:51,077 INFO    MainThread:33176 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'dataloader.py', 'program_abspath': 'E:\\Projects\\CLIP\\dataloader.py', 'program': 'E:\\Projects\\CLIP\\dataloader.py'}
2024-04-08 10:53:51,077 INFO    MainThread:33176 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-04-08 10:53:51,077 INFO    MainThread:33176 [wandb_init.py:_log_setup():521] Logging user logs to E:\Projects\CLIP\wandb\run-20240408_105351-847pdwo2\logs\debug.log
2024-04-08 10:53:51,077 INFO    MainThread:33176 [wandb_init.py:_log_setup():522] Logging internal logs to E:\Projects\CLIP\wandb\run-20240408_105351-847pdwo2\logs\debug-internal.log
2024-04-08 10:53:51,077 INFO    MainThread:33176 [wandb_init.py:init():561] calling init triggers
2024-04-08 10:53:51,077 INFO    MainThread:33176 [wandb_init.py:init():568] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.001, 'epochs': 10, 'batch_size': 64}
2024-04-08 10:53:51,077 INFO    MainThread:33176 [wandb_init.py:init():611] starting backend
2024-04-08 10:53:51,077 INFO    MainThread:33176 [wandb_init.py:init():615] setting up manager
2024-04-08 10:53:51,081 INFO    MainThread:33176 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-04-08 10:53:51,084 INFO    MainThread:33176 [wandb_init.py:init():623] backend started and connected
2024-04-08 10:53:51,091 INFO    MainThread:33176 [wandb_init.py:init():715] updated telemetry
2024-04-08 10:53:51,131 INFO    MainThread:33176 [wandb_init.py:init():748] communicating run to backend with 90.0 second timeout
2024-04-08 10:53:52,573 ERROR   MainThread:33176 [wandb_init.py:init():774] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-04-08 10:53:54,592 ERROR   MainThread:33176 [wandb_init.py:init():1199] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
Traceback (most recent call last):
  File "D:\Anaconda\envs\pytorch0\lib\site-packages\wandb\sdk\wandb_init.py", line 1181, in init
    run = wi.init()
  File "D:\Anaconda\envs\pytorch0\lib\site-packages\wandb\sdk\wandb_init.py", line 780, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-04-08 10:53:56,841 WARNING MsgRouterThr:33176 [router.py:message_loop():77] message_loop has been closed
