2024-04-08 10:55:15,560 INFO    MainThread:29092 [wandb_setup.py:_flush():76] Current SDK version is 0.16.6
2024-04-08 10:55:15,560 INFO    MainThread:29092 [wandb_setup.py:_flush():76] Configure stats pid to 29092
2024-04-08 10:55:15,560 INFO    MainThread:29092 [wandb_setup.py:_flush():76] Loading settings from C:\Users\RyukiRi\.config\wandb\settings
2024-04-08 10:55:15,561 INFO    MainThread:29092 [wandb_setup.py:_flush():76] Loading settings from E:\Projects\CLIP\wandb\settings
2024-04-08 10:55:15,561 INFO    MainThread:29092 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-04-08 10:55:15,561 INFO    MainThread:29092 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-04-08 10:55:15,561 INFO    MainThread:29092 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'dataloader.py', 'program_abspath': 'E:\\Projects\\CLIP\\dataloader.py', 'program': 'E:\\Projects\\CLIP\\dataloader.py'}
2024-04-08 10:55:15,561 INFO    MainThread:29092 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-04-08 10:55:15,561 INFO    MainThread:29092 [wandb_init.py:_log_setup():521] Logging user logs to E:\Projects\CLIP\wandb\run-20240408_105515-4whty4sa\logs\debug.log
2024-04-08 10:55:15,561 INFO    MainThread:29092 [wandb_init.py:_log_setup():522] Logging internal logs to E:\Projects\CLIP\wandb\run-20240408_105515-4whty4sa\logs\debug-internal.log
2024-04-08 10:55:15,561 INFO    MainThread:29092 [wandb_init.py:init():561] calling init triggers
2024-04-08 10:55:15,561 INFO    MainThread:29092 [wandb_init.py:init():568] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.001, 'epochs': 10, 'batch_size': 64}
2024-04-08 10:55:15,561 INFO    MainThread:29092 [wandb_init.py:init():611] starting backend
2024-04-08 10:55:15,561 INFO    MainThread:29092 [wandb_init.py:init():615] setting up manager
2024-04-08 10:55:15,567 INFO    MainThread:29092 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-04-08 10:55:15,569 INFO    MainThread:29092 [wandb_init.py:init():623] backend started and connected
2024-04-08 10:55:15,576 INFO    MainThread:29092 [wandb_init.py:init():715] updated telemetry
2024-04-08 10:55:15,611 INFO    MainThread:29092 [wandb_init.py:init():748] communicating run to backend with 90.0 second timeout
2024-04-08 10:55:16,502 ERROR   MainThread:29092 [wandb_init.py:init():774] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-04-08 10:55:17,325 ERROR   MainThread:29092 [wandb_init.py:init():1199] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
Traceback (most recent call last):
  File "D:\Anaconda\envs\pytorch0\lib\site-packages\wandb\sdk\wandb_init.py", line 1181, in init
    run = wi.init()
  File "D:\Anaconda\envs\pytorch0\lib\site-packages\wandb\sdk\wandb_init.py", line 780, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-04-08 10:55:19,538 WARNING MsgRouterThr:29092 [router.py:message_loop():77] message_loop has been closed
